<img src="https://raw.githubusercontent.com/Kabongosalomon/Data-Science-With-Jeff-Sander/master/aims-za-logo.jpg" width="100" alt="cognitiveclass.ai logo" />

# A simple application of Deep Neural Networks

## In this tutorial I will :

- train a simple neural network that learns the [XNOR function](https://en.wikipedia.org/wiki/Logical_equality), 
- Show how to save a trained neural network and 
- How to load and reuse a saved neural network into the jupyter notebook. 

In [14]:
# Libraries Importation 
from keras.models import Sequential
from keras.layers.core import Dense, Activation
import numpy as np

import base64
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
from sklearn import preprocessing

from keras.models import Sequential
from keras.layers.core import Dense, Activation
import pandas as pd
import io
import requests
import numpy as np

from keras.models import load_model

## Logical equality

Logical equality (also known as biconditional) is an operation on two logical values, typically the values of two propositions, that produces a value of true if both operands are false or both operands are true.

The truth table for p XNOR q (also written as p ↔ q, Epq, p = q, or p ≡ q) is as follows:

![Logical equality](https://raw.githubusercontent.com/Kabongosalomon/Deep-Neural-Networks/master/images/XNORpng.png "Logical equality")

In [19]:
# Create a dataset for the XNOR function
x = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

y = np.array([
    1,
    0,
    0,
    1
])

# Build the network
# sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

done = False
cycle = 1

while not done:
    print("Cycle #{}".format(cycle))
    cycle+=1
    model = Sequential()
    model.add(Dense(2, input_dim=2, activation='relu')) 
    model.add(Dense(1)) 
    model.compile(loss='mean_squared_error', optimizer='adam')
    model.fit(x,y,verbose=0,epochs=10000)

    # Predict
    pred = model.predict(x)
    
    # Check if successful.  It takes several runs with this small of a network
    done = pred[1]<0.01 and pred[2]<0.01 and pred[0] > 0.9 and pred[3] > 0.9 
    print(pred)


Cycle #1
[[0.49999997]
 [0.49999997]
 [0.49999997]
 [0.49999997]]
Cycle #2
[[0.6666666]
 [0.6666666]
 [0.       ]
 [0.6666666]]
Cycle #3
[[9.9999958e-01]
 [4.0972279e-07]
 [2.0802088e-07]
 [9.9999976e-01]]


The output above should have two numbers near 1 for the first and forth spots (input [[0,0]] and [[1,1]]). The middle two numbers should be near 0 (input [[1,0]] and [[0,1]]). These numbers are in scientific notation. Due to random starting weights, it is sometimes necessary to run the above through several cycles to get a good result

In [23]:
pred

array([[9.9999958e-01],
       [4.0972279e-07],
       [2.0802088e-07],
       [9.9999976e-01]], dtype=float32)

In [6]:
y

array([1, 0, 0, 1])

In [21]:
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Before save score (RMSE): {score}")

Before save score (RMSE): 3.324424151302459e-07


# Load/Save Trained Network

In [24]:

from sklearn import metrics
save_path = "./TrainedNet/"

# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Before save score (RMSE): {score}")

# save neural network structure to JSON (no weights)
model_json = model.to_json()
with open(os.path.join(save_path,"XNOR_network.json"), "w") as json_file:
    json_file.write(model_json)

# save entire network to HDF5 (save everything, suggested)
model.save(os.path.join(save_path,"XNOR_network.h5"))

Before save score (RMSE): 3.324424151302459e-07


Now we reload the network and perform another prediction. The RMSE should match the previous one exactly if the neural network was really saved and reloaded.

In [25]:
model2 = load_model(os.path.join(save_path,"XNOR_network.h5"))
pred = model2.predict(x)
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"After load score (RMSE): {score}")

After load score (RMSE): 3.324424151302459e-07


<h2>About the Authors:</h2> 

<a href="https://salomonkabongo.wixsite.com/datascientist">Salomon Kabongo KABENAMUALU</a>, Master degree student at <a href="https://aims.ac.za/">the African Institute for mathematical SCiences (AIMS South Africa)</a> his research focused on the use machine learning technique in the field of Natural Language Processing.

References : <a href="https://sites.wustl.edu/jeffheaton/t81-558/">Jeff Heaton (Wachington University) </a>

Copyright &copy; 2019. This notebook and its source code are released under the terms of the <a href="https://www.apache.org/licenses/LICENSE-2.0/">Apache License 2.0</a>.